## GENERAL

RAY_TRACE_DISTANCE: 7.5

## CHESS

MAX_PLAYERS_CHESS: 2

# Default notation for chess position state - currently supported:
# - FEN
DEFAULT_CHESS_STATE_NOTATION: "FEN"

# Default board setup for chess - uses @DEFAULT_CHESS_STATE_NOTATION
DEFAULT_CHESS_SETUP: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR"

# Default notation for a chess move - currently supported:
# - Algebraic
DEFAULT_CHESS_MOVE_NOTATION: "Algebraic"



## Game Spawn Locations
CHESS_LOCATIONS:
  - { x: -19.42, y: 66.00, z: -154.50, facing: "east"}
SHOGI_LOCATIONS:

# Render mode
RENDER_MODE: "DEBUG"

## Model Data
MODELS:
  DEBUG:
    CHESS:
      K:  # KING
        MODEL_WHITE: OAK_PLANKS
        MODEL_BLACK: DARK_OAK_PLANKS
        SCALE: [0.5, 0.9, 0.5]
      Q:  # QUEEN
        MODEL_WHITE: STRIPPED_OAK_LOG
        MODEL_BLACK: STRIPPED_DARK_OAK_LOG
        SCALE: [0.5, 0.825, 0.5]
      R:  # ROOK
        MODEL_WHITE: OAK_FENCE_GATE
        MODEL_BLACK: DARK_OAK_FENCE_GATE
        SCALE: [0.5, 0.65, 0.5]
      N:  # KNIGHT
        MODEL_WHITE: OAK_STAIRS
        MODEL_BLACK: DARK_OAK_STAIRS
        SCALE: [0.5, 0.7, 0.5]
      B:  # BISHOP
        MODEL_WHITE: OAK_PLANKS
        MODEL_BLACK: DARK_OAK_PLANKS
        SCALE: [0.35, 0.9, 0.35]
      P:  # PAWN
        MODEL_WHITE: OAK_SLAB
        MODEL_BLACK: DARK_OAK_SLAB
        SCALE: [0.4, 0.75, 0.4]

  2D:
  3D:

