## GENERAL



## CHESS

# Default notation for chess position state
DEFAULT_CHESS_STATE_NOTATION: "FEN"
# Default board setup for chess - uses @DEFAULT_CHESS_STATE_NOTATION
DEFAULT_CHESS_SETUP: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR"
# Default notation for a chess move
DEFAULT_CHESS_MOVE_NOTATION: "Algebraic"



