## GENERAL



## CHESS

# Default notation for chess position state - currently supported:
# - FEN
DEFAULT_CHESS_STATE_NOTATION: "FEN"

# Default board setup for chess - uses @DEFAULT_CHESS_STATE_NOTATION
DEFAULT_CHESS_SETUP: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR"

# Default notation for a chess move - currently supported:
# - Algebraic
DEFAULT_CHESS_MOVE_NOTATION: "Algebraic"



## Controller Mappings
CONTROLLER_MAPPINGS:
  chess_debug: "DebugChessSpawner"
  chess_default: "DefaultChessSpawner"



