## GENERAL



## CHESS

# Default notation for chess position state - currently supported:
# - FEN
DEFAULT_CHESS_STATE_NOTATION: "FEN"

# Default board setup for chess - uses @DEFAULT_CHESS_STATE_NOTATION
DEFAULT_CHESS_SETUP: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR"

# Default notation for a chess move - currently supported:
# - Algebraic
DEFAULT_CHESS_MOVE_NOTATION: "Algebraic"



## Game Spawn Locations
CHESS_LOCATIONS:
  - { x: -19.42, y: 66.00, z: -154.50, facing: "east"}
SHOGI_LOCATIONS:


